-- Seed 10 approved job stories for manual testing in Supabase SQL Editor.
-- Safe to run multiple times: rows are upserted by slug.

begin;

insert into public.job_profiles (
  slug,
  role_title,
  industry,
  seniority,
  location,
  work_mode,
  salary_range,
  education_path,
  day_to_day,
  tools_used,
  best_parts,
  hardest_parts,
  recommendation_to_students,
  years_experience,
  submitter_type,
  contact_email,
  status,
  review_notes,
  approved_at,
  approved_by,
  created_at
)
values
  (
    'seed-junior-frontend-developer',
    'Junior Frontend Developer',
    'Software',
    'Entry',
    'Austin, US',
    'hybrid',
    '$68k-$82k',
    'CS degree plus portfolio projects and internship experience',
    'I implement UI tickets, fix browser issues, pair with designers, and write small integration tests for every feature.',
    array['TypeScript', 'React', 'Figma', 'Storybook', 'GitHub'],
    'Fast feedback loops and visible product impact make the role engaging while you build strong technical fundamentals.',
    'Shifting between bugs and planned features can be tiring, especially when release timelines stack in the same week.',
    'Build three complete side projects and explain your tradeoffs clearly so reviewers can trust your engineering decisions.',
    2,
    'public',
    null,
    'approved'::public.profile_status,
    'Seeded for testing',
    now() - interval '9 days',
    null,
    now() - interval '10 days'
  ),
  (
    'seed-registered-nurse-emergency',
    'Registered Nurse (Emergency Care)',
    'Healthcare',
    'Mid',
    'Chicago, US',
    'onsite',
    '$79k-$96k',
    'BSN degree, clinical rotations, and state licensure',
    'I triage incoming patients, administer care plans, monitor vitals, and coordinate with physicians across unpredictable shifts.',
    array['EHR systems', 'Medication scanners', 'Vital monitors'],
    'Direct patient impact and strong team coordination create meaningful work even on difficult days in the emergency unit.',
    'Shift fatigue and emotionally heavy situations can accumulate without consistent recovery habits outside work.',
    'Shadow clinical teams early and evaluate whether shift schedules and high-pressure care decisions match your strengths.',
    6,
    'anonymous',
    null,
    'approved'::public.profile_status,
    'Seeded for testing',
    now() - interval '8 days',
    null,
    now() - interval '9 days'
  ),
  (
    'seed-high-school-math-teacher',
    'High School Math Teacher',
    'Education',
    'Mid',
    'Phoenix, US',
    'onsite',
    '$54k-$67k',
    'Math degree with teaching certification and practicum',
    'I plan lessons, teach mixed-ability classes, grade assignments, and meet families to support student progress and attendance.',
    array['Google Classroom', 'Desmos', 'Spreadsheet trackers'],
    'Seeing students gain confidence over a semester is rewarding and helps you refine communication skills quickly.',
    'Large class sizes and administrative requirements reduce prep time for differentiated teaching approaches.',
    'Tutor consistently before applying so you can assess whether coaching and repetition energize you long term.',
    7,
    'public',
    null,
    'approved'::public.profile_status,
    'Seeded for testing',
    now() - interval '7 days',
    null,
    now() - interval '8 days'
  ),
  (
    'seed-financial-analyst-corporate',
    'Financial Analyst',
    'Finance',
    'Entry',
    'New York, US',
    'hybrid',
    '$78k-$95k',
    'Economics degree and internship in FP&A',
    'I maintain forecast models, explain monthly variance, and prepare summaries that help leaders make budget decisions.',
    array['Excel', 'SQL', 'Power BI', 'NetSuite'],
    'The role builds practical business judgment because your analysis directly affects staffing and investment decisions.',
    'Quarter-end cycles can become intense, and small mistakes in assumptions can quickly propagate.',
    'Practice financial modeling and SQL together because that combination is immediately useful on analyst teams.',
    3,
    'public',
    null,
    'approved'::public.profile_status,
    'Seeded for testing',
    now() - interval '6 days',
    null,
    now() - interval '7 days'
  ),
  (
    'seed-process-engineer-manufacturing',
    'Process Engineer',
    'Manufacturing',
    'Mid',
    'Cleveland, US',
    'onsite',
    '$82k-$101k',
    'Mechanical engineering degree plus Six Sigma training',
    'I investigate defects, tune production steps, and partner with operators to increase throughput while meeting safety requirements.',
    array['Minitab', 'AutoCAD', 'PLC dashboards'],
    'Small process improvements can deliver visible quality gains and cost savings within days.',
    'Troubleshooting during downtime is high pressure and requires calm communication across teams.',
    'Get shop-floor experience early so process decisions are grounded in real operational constraints.',
    8,
    'anonymous',
    null,
    'approved'::public.profile_status,
    'Seeded for testing',
    now() - interval '5 days',
    null,
    now() - interval '6 days'
  ),
  (
    'seed-podcast-producer',
    'Podcast Producer',
    'Media',
    'Mid',
    'Los Angeles, US',
    'remote',
    '$62k-$84k',
    'Communications degree and freelance audio production',
    'I coordinate guests, record episodes, edit audio narratives, and schedule releases with hosts and marketing stakeholders.',
    array['Pro Tools', 'Descript', 'Notion', 'Adobe Audition'],
    'Creative storytelling and audience feedback make the work varied and personally meaningful.',
    'Publishing schedules are demanding, and quality can drop quickly when planning is weak.',
    'Produce a complete season yourself to learn the full lifecycle from recording to promotion.',
    5,
    'public',
    null,
    'approved'::public.profile_status,
    'Seeded for testing',
    now() - interval '4 days',
    null,
    now() - interval '5 days'
  ),
  (
    'seed-city-planning-analyst',
    'City Planning Analyst',
    'Government',
    'Entry',
    'Seattle, US',
    'hybrid',
    '$60k-$76k',
    'Public policy degree with GIS coursework',
    'I review zoning proposals, analyze mobility and housing data, and prepare plain-language briefs for public meetings.',
    array['ArcGIS', 'Tableau', 'Policy memo templates'],
    'Projects can improve neighborhoods directly, which creates strong civic impact and motivation.',
    'Policy cycles are slow and stakeholders can disagree sharply on tradeoffs and priorities.',
    'Practice communicating technical findings clearly because community trust drives planning outcomes.',
    2,
    'public',
    null,
    'approved'::public.profile_status,
    'Seeded for testing',
    now() - interval '3 days',
    null,
    now() - interval '4 days'
  ),
  (
    'seed-retail-store-manager',
    'Retail Store Manager',
    'Retail',
    'Senior',
    'Atlanta, US',
    'onsite',
    '$58k-$73k',
    'Business diploma and internal leadership training',
    'I plan schedules, track sales goals, coach staff, and resolve customer escalations while maintaining inventory accuracy.',
    array['POS systems', 'Inventory software', 'Scheduling tools'],
    'You can shape team culture and service quality directly through daily coaching and accountability.',
    'Peak seasons require long hours, and staffing shortages can affect service quickly.',
    'Part-time customer-facing work builds leadership habits faster than classroom simulations.',
    11,
    'anonymous',
    null,
    'approved'::public.profile_status,
    'Seeded for testing',
    now() - interval '2 days',
    null,
    now() - interval '3 days'
  ),
  (
    'seed-logistics-coordinator',
    'Logistics Coordinator',
    'Logistics',
    'Mid',
    'Memphis, US',
    'hybrid',
    '$55k-$70k',
    'Supply chain degree and warehouse internship',
    'I track shipments, coordinate carriers, resolve delays, and keep inventory and delivery schedules aligned.',
    array['TMS', 'Excel', 'ERP dashboards'],
    'Problem solving is concrete because every fix keeps customers and operations moving.',
    'Unexpected disruptions are daily realities and require calm communication under time pressure.',
    'Build spreadsheet fluency and communication discipline because both are core in operations roles.',
    4,
    'public',
    null,
    'approved'::public.profile_status,
    'Seeded for testing',
    now() - interval '36 hours',
    null,
    now() - interval '48 hours'
  ),
  (
    'seed-renewable-energy-technician',
    'Renewable Energy Technician',
    'Energy',
    'Entry',
    'Denver, US',
    'onsite',
    '$61k-$79k',
    'Electrical technician program and field apprenticeship',
    'I inspect equipment, run preventative maintenance, troubleshoot sensor alerts, and document site performance.',
    array['SCADA dashboards', 'Multimeter', 'Maintenance logs'],
    'Hands-on technical work and visible sustainability impact make the role meaningful and practical.',
    'Weather exposure and travel requirements can be challenging depending on project timelines.',
    'Start with electrical fundamentals and safety practices before advanced renewable-specific specialization.',
    3,
    'public',
    null,
    'approved'::public.profile_status,
    'Seeded for testing',
    now() - interval '24 hours',
    null,
    now() - interval '36 hours'
  )
on conflict (slug) do update
set
  role_title = excluded.role_title,
  industry = excluded.industry,
  seniority = excluded.seniority,
  location = excluded.location,
  work_mode = excluded.work_mode,
  salary_range = excluded.salary_range,
  education_path = excluded.education_path,
  day_to_day = excluded.day_to_day,
  tools_used = excluded.tools_used,
  best_parts = excluded.best_parts,
  hardest_parts = excluded.hardest_parts,
  recommendation_to_students = excluded.recommendation_to_students,
  years_experience = excluded.years_experience,
  submitter_type = excluded.submitter_type,
  contact_email = excluded.contact_email,
  status = excluded.status,
  review_notes = excluded.review_notes,
  approved_at = excluded.approved_at,
  approved_by = excluded.approved_by,
  created_at = excluded.created_at;

commit;
